export const BEGIN_API_CALL = "BEGIN_API_CALL";
export const API_CALL_ERROR = "API_CALL_ERROR";

export const LOAD_REGIONS_SUCCESS = "LOAD_REGIONS_SUCCESS";
export const LOAD_RECORDS_SUCCESS = "LOAD_RECORDS_SUCCESS";
export const LOAD_GROUPED_RECORDS_SUCCESS = "LOAD_GROUPED_RECORDS_SUCCESS";
